# single test suite, non-parallel build.

env:
  global:
    - CC_TEST_REPORTER_ID=9591d3766dbe9b12f62b78bd02c92fe841ff9cd2182c2291ebae0c82ee279070
language: node_js
node_js:
  - "10.14.1"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
